global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: [ 'backend:2112' ]   # /metrics внутри контейнера

#  - job_name: 'node_exporter'
#    static_configs:
#      - targets: [ 'node_exporter:9100' ]

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]
