// Code generated by "enumer -type Role"; DO NOT EDIT.

package model

import (
	"fmt"
	"strings"
)

const _RoleName = "RoleAnonymousRoleAdminRoleUser"

var _RoleIndex = [...]uint8{0, 13, 22, 30}

const _RoleLowerName = "roleanonymousroleadminroleuser"

func (i Role) String() string {
	i -= 1
	if i >= Role(len(_RoleIndex)-1) {
		return fmt.Sprintf("Role(%d)", i+1)
	}
	return _RoleName[_RoleIndex[i]:_RoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RoleNoOp() {
	var x [1]struct{}
	_ = x[RoleAnonymous-(1)]
	_ = x[RoleAdmin-(2)]
	_ = x[RoleUser-(3)]
}

var _RoleValues = []Role{RoleAnonymous, RoleAdmin, RoleUser}

var _RoleNameToValueMap = map[string]Role{
	_RoleName[0:13]:       RoleAnonymous,
	_RoleLowerName[0:13]:  RoleAnonymous,
	_RoleName[13:22]:      RoleAdmin,
	_RoleLowerName[13:22]: RoleAdmin,
	_RoleName[22:30]:      RoleUser,
	_RoleLowerName[22:30]: RoleUser,
}

var _RoleNames = []string{
	_RoleName[0:13],
	_RoleName[13:22],
	_RoleName[22:30],
}

// RoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RoleString(s string) (Role, error) {
	if val, ok := _RoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Role values", s)
}

// RoleValues returns all values of the enum
func RoleValues() []Role {
	return _RoleValues
}

// RoleStrings returns a slice of all String values of the enum
func RoleStrings() []string {
	strs := make([]string, len(_RoleNames))
	copy(strs, _RoleNames)
	return strs
}

// IsARole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Role) IsARole() bool {
	for _, v := range _RoleValues {
		if i == v {
			return true
		}
	}
	return false
}
