httpServer:
  address: "0.0.0.0:8096"
  timeout: 4s
  idleTimeout: 30s
  readHeaderTimeout: 10s
  bodyLimit: 50
authJWT:
  accessExpirationTime: 10h
refresh:
  refreshExpirationTime: 780h
db:
  connectTimeout: 5m
minio:
  useSSL: false
logger:
#  logFilePath:
  environment: local
analyse-client:
  base_url: "http://0.0.0.0:3000/process"
  timeout: 2m
  input_dir: "/inputs"
convert-client:
  base_url: "http://converter:8081/convert"
  timeout: 2m
  input_dir: "/inputs"
