name: CI

on:
  push:
    branches:
      - main

env:
  REGISTRY: "fitzplsr"
  IMAGE_NAME: "mgtu-ecg"
  CONTAINER_NAME: "mgtu-ecg"
  FOLDER_COMPOSE: "mgtu-ecg-deploy"
  GITHUB_SHA_SHORT:


jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: Test with the Go CLI
        run: go test ./...

  build_and_push:
    runs-on: ubuntu-latest
    needs: lint_and_test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | head -c 8)" >> $GITHUB_ENV

      - name: Build and push main
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          file: ./build/Dockerfile
          build-args: |
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            REGISTRY=${{ env.REGISTRY }}
            GITHUB_SHA_SHORT=${{ env.GITHUB_SHA_SHORT }}

